#!/bin/bash

source $HOME/.rcrc

if [[ $TAGS == *"oh-my-zsh"* ]]; then
    if [ ! -d ~/.oh-my-zsh ]; then
      printf "Cloning Oh My Zsh...\n"
      hash git >/dev/null 2>&1 || {
        echo "Error: git is not installed"
        exit 1
      }
      env git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh || {
        printf "Error: git clone of oh-my-zsh repo failed\n"
        exit 1
      }
    fi
fi
