#!/bin/bash
# Source (mostly): https://github.com/thoughtbot/rcm/issues/103#issuecomment-83267499

set -eu

pushd "$(dirname "$0")" > /dev/null
cd ../..
dotfiles_dir="$(pwd)"
popd > /dev/null

if [ ! -f "${HOME}/.rcrc" ]; then
  echo "INFO: Installing default ~/.rcrc file" 1>&2
  cp "${dotfiles_dir}/rcrc" "${HOME}/.rcrc"
fi

if [ ! -d "${HOME}/.rcrc.d" ]; then
  echo "INFO: Creating ~/.rcrc.d folder" 1>&2
  mkdir "${HOME}/.rcrc.d"
  touch "${HOME}/.rcrc.d/example"
fi
