#!/bin/zsh
# Tmux plugin manager

if [ ! -d $HOME/.tmux ]; then
  printf "Cloning tpm...\n"
  hash git >/dev/null 2>&1 || {
    echo "Error: git is not installed"
    exit 1
  }
  env git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || {
    printf "Error: git clone of zplug repo failed\n"
    exit 1
  }
fi
