#!/bin/bash

set -o pipefail
set -o nounset

mkdir -p ~/.config

if [ ! -e ~/.config/nvim ]; then
	echo "Creating symlink ~/.config/nvim -> ~/.vim"
	ln -s ~/.vim ~/.config/nvim
fi

if [ ! -e ~/.config/nvim/init.vim ]; then
	echo "Creating symlink ~/.vimrc -> ~/.config/nvim/init.vim"
	ln -s ~/.vimrc ~/.config/nvim/init.vim
fi

